In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
returns=pd.read_csv(
    "../data/daily_return.csv",
    index_col=0,
    parse_dates=True
)
returns.head()

                AAPL      AMZN     GOOGL      MSFT      NVDA
Date
2020-01-03 -0.009722 -0.012139 -0.005232 -0.012451 -0.016006
2020-01-06  0.007968  0.014886  0.026654  0.002584  0.004194
2020-01-07 -0.004703  0.002092 -0.001932 -0.009118  0.012107
2020-01-08  0.016086 -0.007809  0.007118  0.015928  0.001875
2020-01-09  0.021241  0.004799  0.010498  0.012493  0.010983

In [7]:
mean_returns=returns.mean()*252
mean_returns

AAPL     0.297892
AMZN     0.232658
GOOGL    0.257607
MSFT     0.248931
NVDA     0.768567
dtype: float64

In [6]:
cov_matrix=returns.cov()*252

In [8]:
num_assets=len(mean_returns)
num_assets

5

In [10]:
weights=np.random.random(num_assets)
weights/=np.sum(weights)
weights

array([0.33479672, 0.26429773, 0.26371264, 0.05601233, 0.08118058])

In [11]:
portfolio_return=np.dot(weights,mean_returns)

In [12]:
portfolio_risk=np.sqrt(
    np.dot(
    weights.T,
    np.dot(cov_matrix,weights)
)
)

In [14]:
risk_free_rate=0.04
sharpe=(
    portfolio_return-risk_free_rate)/portfolio_risk
sharpe

np.float64(0.8994124078693341)

In [15]:
portfolio_returns=[]
portfolio_risks=[]
portfolio_sharpes=[]
portfolio_weights=[]

In [17]:
for i in range(10000):
    weights=np.random.random(num_assets)
    weights/=np.sum(weights)
    ret=np.dot(weights,mean_returns)
    risk=np.sqrt(
        np.dot(
           weights.T,
            np.dot(cov_matrix,weights)
        )
    )
    sharpe=(ret-risk_free_rate)/risk
    portfolio_returns.append(ret)
    portfolio_risks.append(risk)
    portfolio_sharpes.append(sharpe)
    portfolio_weights.append(weights)

In [21]:
results=pd.DataFrame({
    "Return": portfolio_returns,
    "Risk": portfolio_risks,
    "Sharpe": portfolio_sharpes
})
results.head()

     Return      Risk    Sharpe
0  0.467635  0.358582  1.192574
1  0.421217  0.332563  1.146301
2  0.326348  0.306552  0.934094
3  0.284281  0.292952  0.833860
4  0.388934  0.320369  1.089163